### ISSUE TITLE
USER STORY: View Order History#11

### ISSUE THREAD

**Issue by mehatabpathan** [mehatabpathan/PP5#12]
As a **site user** I can **view my order history so that I can remember what purchases I've made.**

**Acceptance Criteria:**

a. When the user is logged in and they click on their profile they should see a list of their previous orders.
b. When they click on the order number they should see a detailed breakdown of the order by product.

**Tasks:**

- [ ] Add the users profile to the order in the checkout success view
- [ ]  Update profile html template to include the order history
- [ ]  Link order number to checkout success html page
- [ ]
