### ISSUE TITLE
USER STORY: Payment Details#18

### ISSUE THREAD

**Issue by mehatabpathan** [mehatabpathan/PP5#19]
As a **shopper,** I can **easily enter my payment information securely** so that **I can purchase my chosen products quickly with no issues.**

**Acceptance Criteria:**

a. When the user navigates to the checkout page, they should see the Stripe Elements UI where they can enter their card details securely and pay for their order.
b. The user should receive feedback if the card number is valid/invalid.

**Tasks:**

- [ ] Utilising Stripe Elements, create a Credit Card Details section in the Order Form and embed the Stripe UI component.
- [ ]  Add custom styling to Stripe Elements.
- [ ]  Add Stripe code to Checkout view.
- [ ]  Include Stripe Javascript
- [ ]  Use Stripe Webhooks
