### ISSUE TITLE
USER STORY: View Shopping Bag#19

### ISSUE THREAD

**Issue by mehatabpathan** [mehatabpathan/PP5#20]
As a **shopper** I can **view a the contents of my shopping bag at any time** so I can **see what is included and the total cost.**

**Acceptance Criteria:**

a. When the user clicks on the shopping bag icon in the nav bar they are taken to the shopping bag page.
b. The shopping bag page should show the products which the user has added to their cart, unit price, quantity and subtotal.
c. The user should be able to increase/decrease the quantity of items in the bag.
c. The bag total, delivery costs and then the grand total are displayed at the bottom of the page.
d. The user should have the option to checkout or to continue shopping.

**Tasks:** 

- [ ] Create bag app, HTML template and URL.
- [ ]  Create view_bag view
- [ ]  Add link to shopping bag to the navbar.
- [ ]  Create context.py in the bag app and add to settings.py.
- [ ]  Style bag.html page
