### ISSUE TITLE
USER STORY: Email Confirmation of Purchase#22

### ISSUE THREAD

**Issue by mehatabpathan** [mehatabpathan/PP5#23]
As a **shopper,** I can **receive an email confirmation of my order** so that **I have a record of my purchase.**

**Acceptance Criteria:**

a. When the user has submitted their order they should receive a confirmation email to the email address they entered in their order form.
b. The confirmation email should contain all the details of the order.

**Tasks:**

- [ ] Create email templates for order confirmation
- [ ]  Update webhook handler to handle sending confirmation email
- [ ]  Set up Gmail to send emails
