### ISSUE TITLE
USER STORY: Sort Products#6

### ISSUE THREAD

**Issue by mehatabpathan** [mehatabpathan/PP5#6]
As a **shopper**, I can **sort all products so that I can view products based on price or title.**

**Acceptance Criteria:**

a. Within the browse products page a sort products drop-down menu should appear on the right-hand side.
b. When the user clicks the drop-down arrow a list of pre-defined sort options should appear.
c. When the user selects a sort option the page should display the products in that order.

**Tasks:**

- [ ] Create sort selector on products page and add sort parameters to select box options
- [ ]  Add GET request to the all_products view to sort products
- [ ]  Write javascript to update product list when sort select box is changed
